dist: trusty

language: generic

os: linux

sudo: false

before_install:
- echo 'before_install'

install:
- echo 'install'

before_script:
- echo 'before_script'

script:
- echo 'script'

after_script:
- echo 'after_script'
